export const KSlugIconMapping: Record<string, string> = {
  beauty: 'lipstick',
  fragrances: 'bottle-tonic',
  furniture: 'table-furniture',
  groceries: 'basket',
  'home-decoration': 'home',
  'kitchen-accessories': 'kitchen',
  laptops: 'laptop',
  'mens-shirts': 'tshirt-crew',
  'mens-shoes': 'shoe-formal',
  'mens-watches': 'watch-variant',
  'mobile-accessories': 'headphones',
  motorcycle: 'motorbike',
  'skin-care': 'face-man-shimmer',
  smartphones: 'smartphone',
  'sports-accessories': 'basketball',
  sunglasses: 'sunglasses',
  tablets: 'tablet-mac',
  tops: 'tshirt-v',
  vehicle: 'directions-car-filled',
  'womens-bags': 'handbag',
  'womens-dresses': 'woman-2',
  'womens-jewellery': 'diamond-stone',
  'womens-shoes': 'shoe-heel',
  'womens-watches': 'watch-variant',
  'view-all': 'border-all',
};
